from nemosis.custom_tables import fcas4s_scada_match, plant_stats
from nemosis.data_fetch_methods import _dynamic_data_wrapper_for_gui, _static_table_wrapper_for_gui

_method_map = {
    "DISPATCHLOAD": _dynamic_data_wrapper_for_gui,
    "DISPATCHPRICE": _dynamic_data_wrapper_for_gui,
    "TRADINGLOAD": _dynamic_data_wrapper_for_gui,
    "TRADINGPRICE": _dynamic_data_wrapper_for_gui,
    "TRADINGREGIONSUM": _dynamic_data_wrapper_for_gui,
    "TRADINGINTERCONNECT": _dynamic_data_wrapper_for_gui,
    "DISPATCH_UNIT_SCADA": _dynamic_data_wrapper_for_gui,
    "DISPATCHCONSTRAINT": _dynamic_data_wrapper_for_gui,
    "DUDETAILSUMMARY": _dynamic_data_wrapper_for_gui,
    "PARTICIPANT": _dynamic_data_wrapper_for_gui,
    "DUDETAIL": _dynamic_data_wrapper_for_gui,
    "GENCONDATA": _dynamic_data_wrapper_for_gui,
    "SPDREGIONCONSTRAINT": _dynamic_data_wrapper_for_gui,
    "SPDCONNECTIONPOINTCONSTRAINT": _dynamic_data_wrapper_for_gui,
    "SPDINTERCONNECTORCONSTRAINT": _dynamic_data_wrapper_for_gui,
    "FCAS_4_SECOND": _dynamic_data_wrapper_for_gui,
    "ELEMENTS_FCAS_4_SECOND": _static_table_wrapper_for_gui,
    "VARIABLES_FCAS_4_SECOND": _static_table_wrapper_for_gui,
    "Generators and Scheduled Loads": _static_table_wrapper_for_gui,
    "FCAS Providers": _static_table_wrapper_for_gui,
    "BIDDAYOFFER_D": _dynamic_data_wrapper_for_gui,
    "BIDPEROFFER_D": _dynamic_data_wrapper_for_gui,
    "FCAS_4s_SCADA_MAP": fcas4s_scada_match,
    "PLANTSTATS": plant_stats,
    "DISPATCHINTERCONNECTORRES": _dynamic_data_wrapper_for_gui,
    "DISPATCHREGIONSUM": _dynamic_data_wrapper_for_gui,
    "LOSSMODEL": _dynamic_data_wrapper_for_gui,
    "LOSSFACTORMODEL": _dynamic_data_wrapper_for_gui,
    "MNSP_DAYOFFER": _dynamic_data_wrapper_for_gui,
    "MNSP_PEROFFER": _dynamic_data_wrapper_for_gui,
    "MNSP_INTERCONNECTOR": _dynamic_data_wrapper_for_gui,
    "INTERCONNECTOR": _dynamic_data_wrapper_for_gui,
    "INTERCONNECTORCONSTRAINT": _dynamic_data_wrapper_for_gui,
    "MARKET_PRICE_THRESHOLDS": _dynamic_data_wrapper_for_gui,
    "DAILY_REGION_SUMMARY": _dynamic_data_wrapper_for_gui,
    "NEXT_DAY_DISPATCHLOAD": _dynamic_data_wrapper_for_gui,
    "INTERMITTENT_GEN_SCADA": _dynamic_data_wrapper_for_gui,
    "ROOFTOP_PV_ACTUAL": _dynamic_data_wrapper_for_gui
}
